### ISSUE TITLE
Strange Building Issue on Android Emulator

### ISSUE THREAD

**Issue by PanHyridae** [DoubleDotLabs/ButterySlack#2]
When using certain Android emulators, the app randomly decides not to work. For example: My Nexus 6P emulator crashes, but the 5X emulator works fine, as well as my own Nextbit Robin. This could easily be an issue with my own PC, but I am making this issue here just so I can track it and make sure that it is only a problem on my side.

**Comment by fennifith** [comment]
As seen in the app's [build.gradle](https://github.com/DoubleDotLabs/ButterySlack/blob/master/app/build.gradle), there are a lot of random things I had to do in order to get the Java client library to work, so it could be that one of the things there is messing it up. I'll test the 6P emulator on my laptop later this week to see if it's an actual issue or not. I've only tested it on my HTC so far :P

**Comment by PanHyridae** [comment]
This seems to have fixed itself some how. I will still look into it, but I think it will be OK now.
